version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: university
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
    volumes:
      - mongo_data:/data/db

  mongo_seeder:
    build: ./mongo_seeder
    container_name: mongo_seeder
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://admin:admin@mongo:27017/university?authSource=admin"
    command: ["python", "seed_data.py"]

volumes:
  mongo_data:
